# NumPy Arrays

In [1]:
my_lst = [1,2,3,4,5]

In [2]:
my_lst

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_lst)

In [6]:
arr   # 1-D array

array([1, 2, 3, 4, 5])

In [7]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr_2 = np.array(my_math)

In [9]:
arr_2  # 2-D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2)    # func to create a array with start end and step size are arguments

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)    # 1-D array of all zeros

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3))    # 2-D array taking no of rows and columns as tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,10,20)   # func to create array with evenly distribution between start and end of array, where
                       # where as arrange will take step size as arrgument between start and end 
                       # The array created is 1-D 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
# to create the IDENTITY MATRIX. Identity matrix is square matrix only have element has 0 or 1 and 1's are place at diagnols

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

To create a array consisting of random elements

In [21]:
np.random.rand(5)     # Rand func will create a 1-D or 2-D array with uniform randon distribution between 0 and 1

array([0.74355597, 0.65067043, 0.34001817, 0.48625612, 0.37366097])

In [22]:
np.random.rand(3,3)

array([[0.11745644, 0.91647997, 0.2839608 ],
       [0.02381834, 0.29210137, 0.29223511],
       [0.99147736, 0.75873337, 0.60117731]])

In [23]:
np.random.randn(2,2)  # Func will create a array with element consisting of standard/normal distribution arround 0

array([[ 0.40339756,  0.60654114],
       [-0.01559499,  0.04663803]])

In [25]:
np.random.randint(1,20,5)   # func will create a array with 5 element between 1 and 20. 1 is inclusice and 20 is exclusive

array([12, 18, 12,  6,  6])

Methods and attribute

In [27]:
arr_1 = np.arange(25)

In [28]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ran_arr = np.random.randint(0,100,10)

In [31]:
ran_arr

array([71, 36, 51, 83, 27, 63, 48, 57, 30, 19])

In [32]:
arr_1 = arr_1.reshape(5,5)   # reshapaing the array to 2-D array

In [33]:
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ran_arr = ran_arr.reshape(2,5)

In [35]:
ran_arr

array([[71, 36, 51, 83, 27],
       [63, 48, 57, 30, 19]])

In [44]:
ran_arr.max()     # return the max value in the array

83

In [45]:
ran_arr.argmax()     # return the position of the max value

3

In [49]:
arr_1.max()

24

In [50]:
arr_1.argmax()

24

In [47]:
ran_arr.dtype         # return the element type in array

dtype('int32')

In [128]:
arr_1.shape   # return the shape of the array

(5, 5)

# NumPy Indexing and Selection

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [57]:
arr[5:]   # will grab everthing beyond position 5

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[0:5] = 100  # In array you can broadcasto value to no. of element

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
slice_of_arr = arr[0:6]    # Slicing the array

In [69]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [70]:
slice_of_arr[:] = 99

In [71]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [74]:
arr  

# when we slice the array, data is not copied but create the view of array upto particular position
# when we broadcast the new value in the slice array the changes are done in original array also. 
# the reason numPy does that to avoid extra memory allocation to sliced array in case of large arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
arr_copy = arr.copy()  # COPY will create the new array with same element of original array

In [78]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy[:] = 101

In [83]:
arr_copy   # now the if you broadcast in new array changes are shown in original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing in 2-D array (Matrix)

In [86]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [87]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d[1][1]    # double bracket format

25

In [92]:
arr_2d[1,2]   # single bracket format

30

In [94]:
arr_2d[:2,1:]    # Slicing in 2_D array

array([[10, 15],
       [25, 30]])

Conditional Selection

In [95]:
arr_4 = np.arange(1,11)

In [96]:
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
bool_arr = arr_4 % 2 == 0

In [98]:
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [99]:
arr_4[(bool_arr)]

array([ 2,  4,  6,  8, 10])

In [101]:
arr_4[arr_4 % 2 != 0]    # Coditional Selection in Array

array([1, 3, 5, 7, 9])

In [102]:
arr_5 = np.arange(50).reshape(5,10)

In [103]:
arr_5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
arr_5[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [106]:
arr2d = np.zeros((10,10))

In [107]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
arr_length = arr2d.shape[1]

In [111]:
arr_length

10


# numPy Operation

In [130]:
arr_6 = np.arange(1,11)

In [131]:
arr_6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr_6 + arr_6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [133]:
arr_6 - arr_6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [134]:
arr_6 * arr_6

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Scaler Operation


In [135]:
arr_6 + 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [137]:
arr_6 / arr_6

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])



Universal Array function

In [138]:
np.sqrt(arr_6)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [139]:
np.exp(arr_6)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [140]:
np.tan(arr_6)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [142]:
np.log(arr_6)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])