In [1]:
# Importing the Libraries requried

import numpy as np
import scipy
import sympy
import scipy.linalg

## [1] Solve using RREF and interpret (2 marks)

2x1 − 6x3 = −8 

x2 + 2x3 = 3 

3x1 + 6x2 − 2x3 = −4


In [2]:
# Matrix 'a', Matrix of Coefficent
a1 = np.mat('2,0,-6;0,1,2;3,6,-2')
a1

matrix([[ 2,  0, -6],
        [ 0,  1,  2],
        [ 3,  6, -2]])

In [3]:
# Matrix 'b', matrix of right hand side of the equation

b1 = np.mat('-8;3;-4')
b1

matrix([[-8],
        [ 3],
        [-4]])

In [4]:
# Creating a Augmented matrix

aug1 = sympy.Matrix(np.hstack([a1,b1]))
aug1

Matrix([
[2, 0, -6, -8],
[0, 1,  2,  3],
[3, 6, -2, -4]])

In [5]:
a1_rref,w = aug1.rref()
a1_rref

Matrix([
[1, 0, 0,  2],
[0, 1, 0, -1],
[0, 0, 1,  2]])

In [6]:
a1_det = np.linalg.det(a1)
np.round(a1_det,0)

-10.0

<b>The Value of x1=2,  x2=-1,  x3=2. 
    
    The System is consistent and has unique solution

========================================================================================================================

## [2] What is the rank of this matrix? (2 Marks)


5	3	0

1	2	-4

-2	-4	8



In [7]:
a2 = np.mat('5,3,0;1,2,-4;-2,-4,8')
a2

matrix([[ 5,  3,  0],
        [ 1,  2, -4],
        [-2, -4,  8]])

In [8]:
# Calculatiing the rank of the matrix
 
rank2 = np.linalg.matrix_rank(a2)
print(a2)
print("The Rank of above matrix is:", rank2)

[[ 5  3  0]
 [ 1  2 -4]
 [-2 -4  8]]
The Rank of above matrix is: 2


========================================================================================================================

## [3] Verify Independence of the following vectors (2 Marks)

u	v	w

1	3	0

2	2	4

3	1	8


<b>Solution: 


The following vectors are Independent if:

a1u + a2v + a3w = 0

such that a1 = a2 = a3 =0

In [9]:
mat = np.mat('1,3,0;2,2,4;3,1,8')
mat

matrix([[1, 3, 0],
        [2, 2, 4],
        [3, 1, 8]])

In [10]:
mat0 = np.mat('0;0;0')
mat0

matrix([[0],
        [0],
        [0]])

In [11]:
aug3 = sympy.Matrix(np.hstack([mat,mat0]))
aug3

Matrix([
[1, 3, 0, 0],
[2, 2, 4, 0],
[3, 1, 8, 0]])

In [12]:
mat_rref, w = aug3.rref()
mat_rref

Matrix([
[1, 0,  3, 0],
[0, 1, -1, 0],
[0, 0,  0, 0]])


a1+3a3=0,    
a2-a3=0

<b> Non-Trivial Solution
    
<b> The Above vectors are not linearly Independent

========================================================================================================================

## [4] Find Basis Vectors of the subspace spanned by the following  (2 Marks)

U1 = [1,2,2,-1]

U2 = [1,3,1,1]

U3 = [1,5,-1,5]

U4 = [1,1,4,-1]

U5 = [2,7,0,2]



In [13]:
a4 = np.mat('1,1,1,1,2;2,3,5,1,7;2,1,-1,4,0;-1,1,5,-1,2')
a4

matrix([[ 1,  1,  1,  1,  2],
        [ 2,  3,  5,  1,  7],
        [ 2,  1, -1,  4,  0],
        [-1,  1,  5, -1,  2]])

In [14]:
mat0 = np.mat('0;0;0;0')
mat0

matrix([[0],
        [0],
        [0],
        [0]])

In [15]:
aug4 = sympy.Matrix(np.hstack([a4,mat0]))
aug4

Matrix([
[ 1, 1,  1,  1, 2, 0],
[ 2, 3,  5,  1, 7, 0],
[ 2, 1, -1,  4, 0, 0],
[-1, 1,  5, -1, 2, 0]])

In [16]:
rref4 = aug4.rref()
rref4

(Matrix([
 [1, 0, -2, 0,  1, 0],
 [0, 1,  3, 0,  2, 0],
 [0, 0,  0, 1, -1, 0],
 [0, 0,  0, 0,  0, 0]]),
 (0, 1, 3))

<b> The Basis vectors of the given subspace are:
    
    U1 = [1,2,2,-1]
    
    U2 = [1,3,1,1]
    
    U4 = [1,1,4,-1]

========================================================================================================================

## [5] Calculate the L1 and L2 Norms of this vector 		(2 Marks)

[-4, 3, 0, 2, -1, 5]


In [17]:
a5 = np.array([-4, 3, 0, 2, -1, 5])
a5

array([-4,  3,  0,  2, -1,  5])

In [18]:
# L1 norm ( the sum of the absolute values of the vector.)
l1 = np.linalg.norm(a5,1)

# L2 Norm (he distance of the vector coordinate from the origin of the vector space)
l2 = np.round(np.linalg.norm(a5),1)

In [19]:
print("The L1 norm of the aboce vector is: ", l1)
print("The L2 norm of the aboce vector is: ", l2)

The L1 norm of the aboce vector is:  15.0
The L2 norm of the aboce vector is:  7.4


========================================================================================================================

## [6] What will [4,2] from [1,0], [0,1] basis to a new basis of [2,0] and [0,2]? 

In [20]:
a6_old_basis= np.mat('4;2')
a6_old_basis

matrix([[4],
        [2]])

In [21]:
old_basis = np.mat('1,0;0,1')
old_basis

matrix([[1, 0],
        [0, 1]])

In [22]:
new_basis = np.mat('2,0;0,2')
new_basis

matrix([[2, 0],
        [0, 2]])

(new_basis).(a6_new_basis) = (old_basis).(a6_old_bais)

a6_new_basis = (Inv(new_basis)).((old_basis).(a6_old_bais))

In [23]:
np.dot(old_basis,a6_old_basis)

matrix([[4],
        [2]])

In [24]:
# As per the abpove formula for new basis

a6_new_basis = np.dot(np.linalg.inv(new_basis),(np.dot(old_basis,a6_old_basis)))
a6_new_basis

matrix([[2.],
        [1.]])

In [25]:
print(f"In the new basis {a6_old_basis} will be {a6_new_basis} as seen from original system")

In the new basis [[4]
 [2]] will be [[2.]
 [1.]] as seen from original system


<b> In the new basis [4,2] will be [2,1] as seen from original system

========================================================================================================================

## [7] Compute the L and U components of this matrix (4 Marks)

6	-2	0

9	-1	1

3	7	5


In [26]:
a7 = np.mat('6,-2,0;9,-1,1;3,7,5')
a7

matrix([[ 6, -2,  0],
        [ 9, -1,  1],
        [ 3,  7,  5]])

In [27]:
# Computing the LU Decomposition
p, l, u = scipy.linalg.lu(a7)

In [28]:
# The L Matrix
print("The L matrix is:")
np.round(l,3)

The L matrix is:


array([[ 1.   ,  0.   ,  0.   ],
       [ 0.333,  1.   ,  0.   ],
       [ 0.667, -0.182,  1.   ]])

In [29]:
# The U Matrix
print("The U matrix is:")
np.round(u,3)

The U matrix is:


array([[ 9.   , -1.   ,  1.   ],
       [ 0.   ,  7.333,  4.667],
       [ 0.   ,  0.   ,  0.182]])

In [30]:


np.round(np.matmul(np.matmul(p,l),u))

array([[ 6., -2., -0.],
       [ 9., -1.,  1.],
       [ 3.,  7.,  5.]])

========================================================================================================================

In [31]:
m2 = sympy.Matrix(a7)
m2

Matrix([
[6, -2, 0],
[9, -1, 1],
[3,  7, 5]])

In [32]:
p, l, u = scipy.linalg.lu(m2)

In [33]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.33333333,  1.        ,  0.        ],
       [ 0.66666667, -0.18181818,  1.        ]])

In [34]:
u

array([[ 9.        , -1.        ,  1.        ],
       [ 0.        ,  7.33333333,  4.66666667],
       [ 0.        ,  0.        ,  0.18181818]])

===================================================================================================================

In [36]:
l1,u1,_ = m2.LUdecomposition()

In [37]:
l1

Matrix([
[  1, 0, 0],
[3/2, 1, 0],
[1/2, 4, 1]])

In [38]:
u1

Matrix([
[6, -2, 0],
[0,  2, 1],
[0,  0, 1]])

=========================================================================================================================